version: '3.2'
services:
  operations-ui:
    image: mirantis/operations-ui:latest
    ports:
      - $REACT_APP_PORT:3000
    environment:
      REACT_APP_OPERATIONS_API_URL: 'http://localhost:8001'
      REACT_APP_KEYCLOAK_AUTH_URL: 'http://localhost:8080/auth'
      REACT_APP_KEYCLOAK_REALM: 'demo'
      REACT_APP_KEYCLOAK_CLIENT_ID: 'reactapp'
