version: '3.2'
services:
  operations-ui:
    image: mirantis/operations-ui:latest
    ports:
      - $REACT_APP_PORT:3000
    environment:
      REACT_APP_OPERATIONS_API_URL: 'http://localhost:8001'
