#!/bin/bash

cat >.env.production <<EOL
REACT_APP_OPERATIONS_API_URL=$REACT_APP_OPERATIONS_API_URL
REACT_APP_KEYCLOAK_AUTH_URL=$REACT_APP_KEYCLOAK_AUTH_URL
REACT_APP_KEYCLOAK_REALM=$REACT_APP_KEYCLOAK_REALM
REACT_APP_KEYCLOAK_CLIENT_ID=$REACT_APP_KEYCLOAK_CLIENT_ID
EOL

npm run build --production

serve -l 3000 -s build
